### ISSUE TITLE
Getting warning in console - media isn't playing

### ISSUE THREAD

**Issue by surajgupta1489** [soundblogs/react-soundplayer#10]
Whenever I am trying to play a track from demo page - http://labs.voronianski.com/react-soundplayer/#ExamplePlayers

getting warning in console - Media resource https://api.soundcloud.com/tracks/201675880/stream?client_id=08f79801a998c381762ec5b15e4914d5 could not be decoded.

and media isn't playing, I have been trying in local development and getting the same issue

![screenshot from 2015-09-26 03 41 49](https://cloud.githubusercontent.com/assets/5558630/10113326/bbf48308-6400-11e5-9ec5-afcc557d6773.png)

**Comment by surajgupta1489** [comment]
Seems like only having issues with Firefox browser, For chrome it's working fine.
Version I am using 41.0 - Mozilla Firefox for Ubuntu.

**Comment by surajgupta1489** [comment]
This fixed the issue for me, nothing wrong with the package, Cheers  - [How can I listen to SoundCloud on Linux without Flash?] (http://help.soundcloud.com/customer/portal/articles/1392540-how-can-i-listen-to-soundcloud-on-linux-without-flash-)

**Comment by voronianski** [comment]
:+1:
