### ISSUE TITLE
"pause" and "end" events are tied to the same callback function?

### ISSUE THREAD

**Issue by baka101** [soundblogs/react-soundplayer#12]
In SoundPlayerContainer.js line 62 and 63:

        soundCloudAudio.on('pause', this.onAudioEnded.bind(this));
        soundCloudAudio.on('ended', this.onAudioEnded.bind(this));

And then on line 116 to 121

    onAudioEnded() {
        const { onStopTrack } = this.props;
        this.setState({playing: false});

        onStopTrack && onStopTrack(this.soundCloudAudio);
    }

I'm trying to use the "onStopTrack" method to do something when the song ends.  However, it also gets called every time the song is paused.  Plus, It gets called twice when the song ends... 

Instead of tying 'paused' and 'ended' both to onAudioEnded, should there be an onAudioPaused method?

**Comment by voronianski** [comment]
@baka101 nice catch, I'll fix this ASAP!

**Comment by baka101** [comment]
I made a pull request with the quick change.  Let me know if it's valid.

**Comment by voronianski** [comment]
@baka101 thanks, just updated it with `onPauseTrack` handler and released new version :+1: enjoy!
