### ISSUE TITLE
Going past SoundCloud

### ISSUE THREAD

**Issue by jiku** [soundblogs/react-soundplayer#19]
Not that I think SoundCloud is going anywhere, despite their [funding issues](http://www.nme.com/news/various-artists/91458), but it'd be cool to have some options. A self-hosted Web Audio solution to begin with. I guess it really should be at soundblogs/web-audio, soundblogs/soundcloud-audio, etc? As sources. I'm sure all this is already on your radar somewhere, but just thought I'd open an issue here. Maybe there could be a soundblogs base repo, just for overarall project ideas like these?

**Comment by voronianski** [comment]
@jiku sorry, are you talking about https://github.com/voronianski/soundcloud-audio.js that needed to be more general solution?

**Comment by jiku** [comment]
@voronianski jup. If you'd like to extend the player to be coupled towards other sources as well?

**Comment by voronianski** [comment]
@jiku but what sources are you talking about?) this module is just a simple wrapper around `<audio />` that makes it a little bit easier to work with soundcloud resolve api and data. Though I think it's possible to move some of its' core into separate module but not sure whether it's needed for community.

**Comment by jiku** [comment]
Could be many of the services [here](http://musicmachinery.com/music-apis/). That list is ~3 years old, so maybe not. :) In my case it'd be to stream audio from common remotes like the production server, AWS (S3, Cloudfront, etc), Google Cloud, etc.

Motivation past that might be to future-proof in the event something happens with SC, or some other source. So people aren't too reliant on any particular service, and can easily migrate if they've implemented your player.

I.e. what you wrote about moving anything service-specific out of the player core and into seperate, service-specific modules that wrap it.

No idea if anyone else is interested in a more generic player like that either, or if some other React project would be a better candidate for it.

**Comment by voronianski** [comment]
@jiku in plans I have a blog post about react-soundplayer and tutorial on how using it with different services (not only SoundCloud) but for now I'm closing this issue.
