### ISSUE TITLE
progress doesn't seem to be updated

### ISSUE THREAD

**Issue by anchetaWern** [soundblogs/react-soundplayer#20]
I can't seem to get the progress bar to work. Something was mentioned about passing in the `soundCloudAudio` prop but I'm not really sure how to do it.

var client_id = 'xxxx';
var stream_url = 'https://api.soundcloud.com/tracks/200494743/stream';

<SoundPlayerContainer streamUrl={stream_url} clientId={client_id}>
  <PlayButton className="orange-button" />
  <Timer />
  <Progress />
</SoundPlayerContainer>

Here's a screenshot of the output while the audio is played:
![width](https://cloud.githubusercontent.com/assets/743603/13378491/6e729030-de43-11e5-8bd6-aff657c91d08.png)

**Comment by voronianski** [comment]
@anchetaWern did you check the example player with progress - https://github.com/soundblogs/react-soundplayer/blob/master/examples/players/ProgressSoundPlayer.js ?

**Comment by anchetaWern** [comment]
thanks! I didn't see that. It's working now. I'm closing this.

**Comment by dnlsandiego** [comment]
Having the same issue. Checked the example player but nothing in there stands out to be something I am missing. @anchetaWern Can you share you fix? @voronianski Has the progress API changed?
