### ISSUE TITLE
Progress bar not updating

### ISSUE THREAD

**Issue by dnlsandiego** [soundblogs/react-soundplayer#28]
Having the same issue as #20 but no solution so far. The progress bar is just at max 100% instead of starting a 0 and progressing along with the song playing. No errors in the console as well. I'm probably just missing a proper usage of the component but I'm going along with the docs. 

I made a repo to reproduce this issue: [react-soundplayer-progress-component-issue](https://github.com/dnlsandiego/react-soundplayer-progress-component-issue)

A quick glance on the code in the repo:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { PlayButton, Progress } from 'react-soundplayer/components';
import { SoundPlayerContainer } from 'react-soundplayer/addons';

const clientId = 'xxx';
const resolveUrl = 'https://soundcloud.com/xxx/josh-j-all-i-know';

class AppPlayer extends React.Component {
	render() {

		let { track, currentTime, duration } = this.props; // These are all undefined for some reason.

		return (
			<SoundPlayerContainer resolveUrl={resolveUrl} clientId={clientId}>
				<PlayButton />
				<Progress 
                    value={currentTime / duration * 100 || 0}
                    soundcloudAudio={this.props.soundcloudAudio}
                    {...this.props}
                />
			</SoundPlayerContainer>
		)
	}
}

ReactDOM.render(
	<AppPlayer />,
	document.querySelector('.app')
);
```

Another issue I'm having is that the `track`, `currentTime` and `duration` props are all undefined.

**Comment by voronianski** [comment]
@dnlsandiego did you figure out what was wrong?

**Comment by dnlsandiego** [comment]
@voronianski I did. It was mainly my usage of the components that was causing the problem and that the README docs are quite outdated, mainly the `Progress` part.

Looking at the `Progress` component, I'm getting that its meant to have a `value` prop passed in to control the progression but `SoundPlayerContainer` doesn't automagically pass that value in; which is fine but when using `Progress` as a immediate child of `SoundPlayerContainer`, `Progress` would need a intermediary component that has access to `currentTime` and `duration` to calculate the progress of the track and pass the result in as `value` to `Progress`. 

Maybe reworking the `Progress` component to handle `value` internally instead of relaying it to be passed in would be better? It would also be more inline with the other components in the sense that just using them under `SoundPlayerContainer` would make them automagically work.

**Comment by voronianski** [comment]
@dnlsandiego solved by https://github.com/soundblogs/react-soundplayer/pull/30
