### ISSUE TITLE
Fleshing out getting started section?

### ISSUE THREAD

**Issue by osuosu** [soundblogs/react-soundplayer#31]
I'm really stuck even trying to get the demos for this sorted. Is there any way you could do add more details like a step-by-step introduction on how to properly set this up on something like on a local MAMP set up?

Thanks,

Osu

**Comment by voronianski** [comment]
@osuosu I plan to create a blog post that will cover this issue https://github.com/soundblogs/react-soundplayer/issues/33 and also some sort of getting started. 

For now you can check this tutorial which describes how to use module in electron app - https://www.sitepoint.com/music-streaming-app-electron-react-es6/. 

Also check pls the example players and how they are structured - https://github.com/soundblogs/react-soundplayer/tree/master/examples/players.
