### ISSUE TITLE
Can i use raw MP3 with this library ?

### ISSUE THREAD

**Issue by sascha1337** [soundblogs/react-soundplayer#33]
Hi, what if i don't want to play a soundcloud link - instead i have served mp3 on my server.
is this possible with this library or is this the wrong repo

thx !

**Comment by crr** [comment]
Have the same question, would love to know if there is any way to use this with self-hosted files.

**Comment by voronianski** [comment]
@sascha1337 @crr it's possible to use library's [pure components](https://github.com/soundblogs/react-soundplayer#pure-components) with self-hosted mp3 files. You will need to create your own container component that will deal with audio and pass props to the components.

Probably I will create a tutorial to demonstrate how it works and will put few lines in README as well.

**Comment by mxmtsk** [comment]
+1 because the player looks just super cool!

**Comment by adamwan92** [comment]
Any ideas how to do this? Would like to use raw MP3s as well

**Comment by alekseychaikovsky** [comment]
anyone manage to put something together with raw mp3s and have an example?

**Comment by voronianski** [comment]
Now you can use custom audio source - https://github.com/soundblogs/react-soundplayer#custom-audio-example, just update to latest `1.0.0`.
