### ISSUE TITLE
react-soundplayer + Ionic

### ISSUE THREAD

**Issue by judsonbomfim** [soundblogs/react-soundplayer#4]
I'm new in the development of apps and use various plugins to play SoundCloud in an application with Ionic.

In several are giving a delay of 10s to start the audio.

I tried using Plangular, but the author pointed me this plugin,

I tried to use this plugin, the could not implement.

Someone would have an example to implement this plugin with Ionic?

I thank you!

**Comment by voronianski** [comment]
@judsonbomfim I can only advice you to take a look on https://github.com/davidchang/ngReact which makes possible to use react components inside of angular apps.
