### ISSUE TITLE
Upgrade to React 15.x

### ISSUE THREAD

**Issue by joao-gsneto** [soundblogs/react-soundplayer#48]
Try to install in react 15.1.x project

npm ERR! peerinvalid Peer react-soundplayer@0.3.6 wants react@^0.14.x

**Comment by voronianski** [comment]
@joao-gsneto will do ASAP.

**Comment by joewestcott** [comment]
I've been having issues in with SVGs in react v15.2, something that was fixed in v15.3 by the way.

**Comment by voronianski** [comment]
@joewestcott 15.3 is our goal then :)

**Comment by joewestcott** [comment]
or `^0.14.8 || ^15.3.0`?

**Comment by voronianski** [comment]
@joao-gsneto @joewestcott updated the package with npm with React v15 support. It's with `prerelease` tag for now because I want to add few resolved issues into v1. Install it like `npm i react-soundplayer@prerelease`.
