### ISSUE TITLE
react sound cloud not working on android

### ISSUE THREAD

**Issue by jisaac89** [soundblogs/react-soundplayer#5]
Not working on a Samsung s6, also any chance you can provide a guide on how to set up multiple soundcloud player instances that are controlled through one parent? for example i have multiple players but I can play each one individually, when the case I want is that playing one song should pause all the other players. Other than that this component is awesome!

**Comment by voronianski** [comment]
@jisaac89 thanks!

What version of android? Does it support html5 audio? It will be very handy to see some traceback.

> to set up multiple soundcloud player instances that are controlled through one parent?

Check example on http://labs.voronianski.com/react-soundplayer/ `SoundPlayerContainer` (https://github.com/soundblogs/react-soundplayer#soundplayercontainer) handles that for you.
