### ISSUE TITLE
How umount (or pause) component after change page or call a action?

### ISSUE THREAD

**Issue by joao-gsneto** [soundblogs/react-soundplayer#52]
I'm developing a custom player and /play is a custom route and render a soundcloud component.
But on change URL, click back or hide the app the soundplayer stills playing the song, even by setting the sound to null onDidUnmount action.

I can programmatically invoke an action to stop the player?

```
  componentWillUnmount: function() {
    this.setState({song:''}); //need to stop the player calling a action here
  },

  render: function() {
    var track = this.state.song;
    var currentTime = 0;
    var client = SOUNDCLOUD_ID;

    return (
      <div key="div_playSong">
        <div className="image" style={{ margin: '2em auto', width: '50%' }}>
          <img src={this.state.song.artwork_url} />
        </div>

        <h1>
          Musica:
          {this.state.song.title}
        </h1>
         <SoundPlayerContainer streamUrl={this.state.song.stream_url} clientId={client}>
<PlayButton className="flex-none h4 mr2 button button-transparent button-grow rounded" {...this.props} />
                <h2 className="h5 nowrap caps flex-auto m0">{track ? track.title : 'Loading...'}</h2>
<Timer className="h6 mr1" duration={track ? track.duration / 1000 : 0} currentTime={currentTime} {...this.props} />
         </SoundPlayerContainer>
      </div>
    );
  }
```

**Comment by adamwan92** [comment]
@joao-gsneto Hey man, i saw that you closed this issue. Did you manage to figure it out?

**Comment by joao-gsneto** [comment]
@adamwan92 just configure a unique key for the player component for all of your songs, so, when you change the component to another song the player change and work well.

**Comment by adamwan92** [comment]
Cool, thanks for the reply! Will try that out too. I also figured out how to pause the player when unmounting the component:

`componentWillUnmount(){
      let { soundCloudAudio } = this.props;
      soundCloudAudio && soundCloudAudio.pause();
    }`
