### ISSUE TITLE
Doesn't work in ie11 

### ISSUE THREAD

**Issue by magicspon** [soundblogs/react-soundplayer#53]
Hello,

I'm having issues getting this to work with IE11.  The demo site is also not working in ie11.  Pressing play on the examples doesn't do anything. 

The error is in the _jsonp function

`script.src = _appendQueryParam(url, 'callback', id);`

IE throws error saying 'invalid property type'

Any thoughts?

**Comment by magicspon** [comment]
Can anyone shed any light on this?  

I've made a copy of soundcloud-audio and changed the jsonp function to use a promise based one (fetch-jsonp) and I'm getting pretty much the same error.  

I've also noticed that a few other soundcloud react components aren't working in ie11.  Wondering if something on the soundcloud side of things is borked.

waaaaa! :(

**Comment by superhighfives** [comment]
Ran into the same problem on https://koya.brailleface.co, but it looks like it's an issue with the https://github.com/voronianski/soundcloud-audio.js/ package. 

I've rolled back to soundcloud-audio 0.1.7 and it's working fine.
