### ISSUE TITLE
Trigger Next Button with onAudioEnded()  ?

### ISSUE THREAD

**Issue by a-s-f** [soundblogs/react-soundplayer#56]
Hey guys I am still new to react and wondering how to make this happen, I am stuck in jQuery ways.

**Comment by voronianski** [comment]
@a-s-f just `onStopTrack` prop:

- https://github.com/soundblogs/react-soundplayer/blob/master/src/addons/withSoundCloudAudio.js#L115
- http://labs.voronianski.com/react-soundplayer/#SoundPlayerContainer
