### ISSUE TITLE
SoundPlayerContainer Not Displaying Iframe

### ISSUE THREAD

**Issue by Chase-Klingel** [soundblogs/react-soundplayer#63]
Hi, I would love to get some help. Below is my code and nothing renders. There is also no errors in the console. I took the example directly from the example page. Any ideas why this wouldn't be rendering? I absolutely love the look of some of your sc players and would really love to use this!

`import React from 'react';
import { SoundPlayerContainer } from 'react-soundplayer/addons';
const clientId = 'MY_CLIENT_ID';
const resolveUrl = 'https://soundcloud.com/thrilljockey/future-islands-balance';

export default class Widget extends React.Component {
  constructor(){
      super();
      this.trackReady = this.trackReady.bind(this);
  }

  trackReady(){
      console.log('Track can be played!')
      // Enable the play button, or start playing programmatically, etc
  }

  render() {
    return (
      <div className="col s12 m6">
        <SoundPlayerContainer
          clientId={clientId}
          resolveUrl={resolveUrl}
          onReady={this.trackReady}
        >
        </SoundPlayerContainer>
      </div>
    )
  }
}`

I also noticed that the onReady never fires.

**Comment by voronianski** [comment]
Your `render` method is not returning nothing, is it by mistake? And `onReady` callback works in 1.0.0 that will be in npm asap.
