### ISSUE TITLE
Continue reading playlist after track's end

### ISSUE THREAD

**Issue by gpoulet** [soundblogs/react-soundplayer#64]
Hello,

Congratulations for your job ! Integration with my web site was relatively simple.

However, when a track is finish, the player doesn't read the next track. Is it normal ? How can I do that ?

Best regards,

**Comment by gangstafat** [comment]
I'm having the same problem too.

**Comment by voronianski** [comment]
Please take a look on the example implementation with playlist https://github.com/soundblogs/react-soundplayer/blob/master/examples/players/PlaylistSoundPlayer.js 

You need to implement managing of active playlist index in player's state by yourself. As you can see in the example below it's just a matter of using proper components and callbacks:

```js
nextIndex() {
  let { activeIndex } = this.state;
  let { playlist } = this.props;
  
  if (activeIndex >= playlist.tracks.length - 1) {
    return;
  }

  if (activeIndex || activeIndex === 0) {
    this.setState({activeIndex: ++activeIndex});
  }
}

prevIndex() {
  let { activeIndex } = this.state;
  if (activeIndex <= 0) {
    return;
  }

  if (activeIndex || activeIndex === 0) {
    this.setState({activeIndex: --activeIndex});
  }
}
```

**Comment by gpoulet** [comment]
My fix (it's never too late ;-) ) : 
add to PlaylistSoundPlayer.js :
 ```
 constructor(props) {
    super(props)
    this.onAudioEnded =  this.onAudioEnded.bind(this)
  }

  componentDidMount() {
    const { soundCloudAudio } = this.props
    soundCloudAudio.on('ended', () => this.onAudioEnded())
  }

  onAudioEnded() {
    const { soundCloudAudio } = this.props
    soundCloudAudio && soundCloudAudio.play({ playlistIndex: soundCloudAudio._playlistIndex+1 });
  }

```
