### ISSUE TITLE
Safari issue loading SoundCloud audio stream

### ISSUE THREAD

**Issue by jhawbrey** [soundblogs/react-soundplayer#66]
Safari 9.1.2 is not able to return SoundCloud stream due to the following error:

```
XMLHttpRequest cannot load https://api.soundcloud.com/tracks/196316910.json?client_id=08f79801a998c381762ec5b15e4914d5. Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.
```

I built the current /examples and was able to replicate the issue. This issue does NOT occur on the older /examples that is hosted at http://labs.voronianski.com/react-soundplayer/.

**Comment by voronianski** [comment]
It was issue related to https://github.com/voronianski/soundcloud-audio.js/issues/16.
