### ISSUE TITLE
Missing VolumeControl Component

### ISSUE THREAD

**Issue by akaipham** [soundblogs/react-soundplayer#67]
I just clean install this package, but when I:
`import { PlayButton, Progress, VolumeControl, Icons } from 'react-soundplayer/components';`
It yields error missing VolumeControl. I watched the folder module/lib/component, and ya, it's missing this component...

**Comment by cmmartin** [comment]
The npm build hasn't been updated in 11 months. There is also no `withSoundCloudAudio` addon in the npm version

@voronianski can you publish the latest to npm?

**Comment by voronianski** [comment]
@akaipham @cmmartin pls use latest rc version for now (e.g. `npm ls react-soundplayer` to list all versions), `1.0.0-rc4` is the latest.
