### ISSUE TITLE
add 'ended' event callback  

### ISSUE THREAD

**Issue by wajerrr** [soundblogs/react-soundplayer#69]
Hi,
I have started using your component few weeks ago in my own project.
It is amazing!

I am not sure if anyone else would find useful to add callback for 'ended' event

in my case I need it to create custom playlist (array of SC tracks playing next one on previous ended)
I would be super happy to contribute and make PR with this change,
if you find it  helpful/ useful
cheers

**Comment by voronianski** [comment]
@wajerrr it's not documented but you can use it - https://github.com/soundblogs/react-soundplayer/blob/master/src/addons/SoundPlayerContainer.js#L35-L36

**Comment by voronianski** [comment]
Stay tuned for upcoming updates and new docs!
