### ISSUE TITLE
Support all tracks resolveUrl

### ISSUE THREAD

**Issue by kirill-konshin** [soundblogs/react-soundplayer#8]
Soundcloud has all tracks page for the artist:

```
https://soundcloud.com/%artistName%/tracks
```

I suppose SoundPlayer should support this too.

**Comment by voronianski** [comment]
@kirill-konshin it's related to https://github.com/voronianski/soundcloud-audio.js and not the component itself

**Comment by voronianski** [comment]
https://github.com/voronianski/soundcloud-audio.js/issues/3

**Comment by voronianski** [comment]
@kirill-konshin support is added, enjoy :wink:

**Comment by kirill-konshin** [comment]
Thank you!

**Comment by voronianski** [comment]
@kirill-konshin FYI notice that such urls respose misses the data that is usually present in soundcloud `playlist` object.
