### ISSUE TITLE
Make SoundPlayerContainer as Higher Order Components or use context instead of magically wrapping children

### ISSUE THREAD

**Issue by kirill-konshin** [soundblogs/react-soundplayer#9]
https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750
or
http://browniefed.com/blog/2015/05/02/react/
or 
https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

Much cleaner approach...

**Comment by voronianski** [comment]
@kirill-konshin actually SoundPlayerContainer IS a high-order component but I agree that using `context` will be much cleaner. 

I've choosen `props` because `context` had a smell of internal thing. Probably I'll switch to context in next major version (PRs are also welcome).

**Comment by kirill-konshin** [comment]
They're going to make it publicly available, so it's the same kind of thing as `props`.

**Comment by kirill-konshin** [comment]
In React 0.14 some additional context improvements were added.

Also you may want to take a look on React DND project: http://gaearon.github.io/react-dnd/ as an example of `@Decorators`.

**Comment by voronianski** [comment]
Added in `react-soundplayer@1.0.0-rc4`.
